
  
SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE CARGAR_CATEGORIA(FILAS OUT SYS_REFCURSOR)
AS
  BEGIN
    OPEN FILAS FOR SELECT ID_CATEGORIA AS CODIGO,DESCRIPCION FROM CATEGORIA;
  END;
  
  
CREATE OR REPLACE PROCEDURE CARGAR_PRODUCTOS(FILAS OUT SYS_REFCURSOR)
AS
  BEGIN
    OPEN FILAS FOR
    SELECT ID_PRODUCTO, NOMBRE, IMP_PRODUCTO, TARIFA_IMP, DESC_PRODUCTO, PRECIO_UNITARIO, DESCRIPCION, PROVEEDOR 
    FROM PRODUCTOS,CATEGORIA 
    WHERE CATEGORIA_ID = ID_CATEGORIA;
  END;
  

CREATE OR REPLACE PROCEDURE CARGAR_CLIENTES(FILAS OUT SYS_REFCURSOR)
AS
  BEGIN
    OPEN FILAS FOR SELECT CEDULA,NOMBRE,APELLIDOS,TELEFONO,CORREO_ELECTRONICO,DIRECCION FROM CLIENTES;
  END;
  





